import { defineConfig } from 'vite';
import { readFileSync } from 'fs';
import { URL } from 'url';

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'));

// Files that come from public/ as they are (not part of the bundle) and the
// phone app needs offline.
const PUBLIC_FILES = ['manifest.webmanifest', 'favicon.png', 'apple-touch-icon.png', 'icon-192.png', 'icon-512.png', 'white-eagles-logo-white.webp'];

// Service worker of the phone app: keeps every built file, serves them
// offline, and lets requests to Google go to the network untouched. The page
// itself is taken from the network first, because it names the current
// files; a new version arrives as a new cache.
function serviceWorkerSource(version, files) {
  return `// Generated by the build: WE Budget ${version}
const CACHE = 'we-budget-${version}';
const FILES = ${JSON.stringify(files)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith('we-budget-') && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request)
      .then(response => {
        const copy = response.clone();
        caches.open(CACHE).then(cache => cache.put('./', copy));
        return response;
      })
      .catch(() => caches.match('./')));
    return;
  }
  event.respondWith(caches.match(request).then(hit => hit || fetch(request).then(response => {
    if (response.ok) {
      const copy = response.clone();
      caches.open(CACHE).then(cache => cache.put(request, copy));
    }
    return response;
  })));
});
`;
}

function serviceWorker(version) {
  return {
    name: 'we-budget-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      // Fonts come in many alphabets; the browser loads only the ones a page
      // needs, and the worker keeps them as they are first used.
      const built = Object.keys(bundle).filter(name => !name.endsWith('.map') && name !== 'index.html' && !/\.woff2?$/.test(name));
      const files = ['./', ...built.map(name => './' + name), ...PUBLIC_FILES.map(name => './' + name)];
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: serviceWorkerSource(version, files) });
    }
  };
}

export default defineConfig(({ mode }) => {
  // mode "web": the phone and browser app, published at
  // https://jaffarsk24.github.io/WE-Budget/app/
  const web = mode === 'web';
  return {
    base: web ? '/WE-Budget/app/' : '/',
    // App version comes from package.json, the single source of truth.
    define: {
      __APP_VERSION__: JSON.stringify(pkg.version),
      __WEB_BUILD__: JSON.stringify(web)
    },
    plugins: web ? [serviceWorker(pkg.version)] : [],
    build: {
      outDir: web ? 'dist-web' : 'dist',
      rollupOptions: {
        output: {
          // Heavy vendors in their own chunks so app code caches independently.
          manualChunks: {
            chart: ['chart.js/auto'],
            icons: ['lucide']
          }
        }
      }
    },
    server: {
      port: 3010,
      strictPort: true,
      open: false
    }
  };
});
